### ISSUE TITLE
Clone repo from GitHub to local machine

### ISSUE THREAD

**Issue by heorhi-kamarou** [clarity-project/clarity-crm#3]
## Install local copy of project from GitHub
- [x] Use `git clone` to pull repo's code 
- [x] Create SSH keys and set it into GitHub profile section with [SSH Keys](https://github.com/settings/keys). [Help article](https://help.github.com/articles/connecting-to-github-with-ssh/)
- [x] Use `git config` to set your credentials

**Comment by Anatoliy2017** [comment]
done
